name: Keep Alive

on:
  schedule:
    - cron: '0 0 1 * *'  # Corre el día 1 de cada mes
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Keep workflows active
        run: echo "Keeping workflows active - $(date)"
